import { QuestionItem, QuestionDifficulty } from "./question-bank-types";

export type { QuestionItem, QuestionDifficulty };

export const ALL_COMPANIES = [
  "All Companies",
  "Google",
  "Microsoft",
  "Amazon",
  "Meta",
  "Apple",
  "Adobe",
  "Oracle",
  "Salesforce",
  "Uber",
  "Atlassian",
  "Flipkart",
  "Walmart",
  "Goldman Sachs",
  "Morgan Stanley",
  "JPMorgan",
  "Deloitte",
  "Accenture",
  "TCS",
  "Infosys",
  "Wipro",
  "Cognizant",
  "Capgemini",
  "ServiceNow",
  "Qualcomm",
  "NVIDIA",
  "Samsung",
  "Intel",
  "Cisco"
] as const;

export const ALL_ROLES = [
  "All Roles",
  "Software Engineer",
  "SDE",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Data Scientist",
  "ML Engineer",
  "AI Engineer",
  "Data Analyst",
  "Product Manager",
  "DevOps Engineer",
  "Cloud Engineer",
  "Cybersecurity Engineer"
] as const;

export const ALL_ROUNDS = [
  "All Rounds",
  "Online Assessment",
  "Coding Round",
  "Technical Round 1",
  "Technical Round 2",
  "Technical Round 3",
  "System Design",
  "Machine Coding",
  "Managerial",
  "HR",
  "Behavioral",
  "Group Discussion",
  "Aptitude",
  "Other"
] as const;

export const ALL_QUESTION_TYPES = [
  "All Types",
  "Coding",
  "DSA",
  "MCQ",
  "Conceptual",
  "Debugging",
  "Output prediction",
  "SQL",
  "System Design",
  "AI/ML",
  "GenAI",
  "OOP",
  "DBMS",
  "Operating Systems",
  "Computer Networks",
  "Web Development",
  "Aptitude",
  "Logical Reasoning",
  "HR / Behavioral",
  "Situational"
] as const;

export const QUESTION_CATEGORIES = [
  "DSA",
  "OOP",
  "DBMS",
  "Operating Systems",
  "Computer Networks",
  "Programming",
  "AI / ML",
  "Generative AI",
  "Web Development",
  "HR / Behavioral",
  "Aptitude",
  "System Design"
] as const;

export const ALL_QUESTION_BANK_ITEMS: QuestionItem[] = [
  // ─── 1. DSA (ARRAYS, TWO POINTERS, SLIDING WINDOW) ─────────────────
  {
    id: "qb-dsa-001",
    title: "Trapping Rain Water (Two Pointer Optimization)",
    question: "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
    type: "Coding",
    company: "Google",
    role: "Software Engineer",
    round: "Technical Round 2",
    domain: "DSA",
    topic: "Arrays",
    subtopic: "Two Pointers",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Google Onsite Engineering Interview",
    verified: true,
    codeSnippet: `int trap(vector<int>& height) {\n  int left = 0, right = height.size() - 1;\n  int leftMax = 0, rightMax = 0, water = 0;\n  while (left < right) {\n    if (height[left] < height[right]) {\n      height[left] >= leftMax ? leftMax = height[left] : water += leftMax - height[left];\n      left++;\n    } else {\n      height[right] >= rightMax ? rightMax = height[right] : water += rightMax - height[right];\n      right--;\n    }\n  }\n  return water;\n}`,
    testCases: [
      { input: "height = [0,1,0,2,1,0,1,3,2,1,2,1]", expectedOutput: "6" },
      { input: "height = [4,2,0,3,2,5]", expectedOutput: "9" }
    ],
    hints: [
      "Water trapped at index i is determined by min(max_left, max_right) - height[i].",
      "Instead of precomputing arrays in O(N) space, can you move pointers from both ends towards the highest peak?"
    ],
    explanation: "Using two pointers (left at 0, right at n-1), we track the maximum heights seen from both sides. We advance the pointer with the smaller boundary because water capacity on that side is strictly bounded by its local maximum.",
    solution: "Initialize left=0, right=n-1, leftMax=0, rightMax=0. While left < right, if height[left] < height[right], update leftMax or accumulate water += leftMax - height[left], then left++. Symmetrically for right pointer. Runtime is strictly O(N) with O(1) auxiliary space.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    tags: ["Arrays", "Two Pointers", "Dynamic Programming", "Google", "Amazon"],
    recommendedForRoles: ["Software Engineer", "Backend Developer", "AI/ML Engineer"],
    whyRecommended: "Tests optimal pointer progression and computational geometry under memory constraints.",
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dsa-002",
    title: "LRU Cache Implementation with O(1) Operations",
    question: "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache supporting get(key) and put(key, value) in strictly O(1) time.",
    type: "Coding",
    company: "Amazon",
    role: "SDE",
    round: "Technical Round 1",
    domain: "DSA",
    topic: "Hash Map",
    subtopic: "Doubly Linked List",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Amazon SDE-1 Technical Round",
    verified: true,
    testCases: [
      { input: "LRUCache(2); put(1,1); put(2,2); get(1); put(3,3); get(2);", expectedOutput: "[null, null, null, 1, null, -1]" }
    ],
    hints: [
      "You need O(1) lookup: what data structure does that? Hash Map.",
      "You need O(1) reordering and eviction of the least recently used item: what data structure does that? Doubly Linked List with head/tail sentinels."
    ],
    explanation: "A Hash Map provides O(1) lookup from key to node. A Doubly Linked List allows O(1) removal and insertion at the head. By combining them, every get moves the node to head, and put evicts the tail node when capacity is exceeded.",
    solution: "Maintain head and tail dummy sentinel nodes. On get(k): if k exists in map, removeNode(node), addNodeToHead(node), return node.val; else return -1. On put(k, v): if k exists, update value and moveToHead; if new, create node, addToHead, add to map. If size > capacity, removeTail() and delete from map.",
    timeComplexity: "O(1) for both get and put",
    spaceComplexity: "O(Capacity)",
    tags: ["Hash Map", "Doubly Linked List", "System Design", "Amazon", "Flipkart"],
    recommendedForRoles: ["Software Engineer", "Backend Developer", "SDE"],
    whyRecommended: "Directly tests hybrid data structure composition and cache eviction policies critical for backend API performance.",
    createdAt: "2025-02-10T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dsa-003",
    title: "Longest Substring Without Repeating Characters",
    question: "Given a string s, find the length of the longest substring without duplicate characters.",
    type: "Coding",
    company: "Microsoft",
    role: "Software Engineer",
    round: "Online Assessment",
    domain: "DSA",
    topic: "Strings",
    subtopic: "Sliding Window",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Microsoft Codility Assessment 2025",
    verified: true,
    testCases: [
      { input: "s = 'abcabcbb'", expectedOutput: "3" },
      { input: "s = 'bbbbb'", expectedOutput: "1" },
      { input: "s = 'pwwkew'", expectedOutput: "3" }
    ],
    hints: [
      "Use a sliding window [start, end]. Maintain a hash map of character to its latest seen index.",
      "When a duplicate is encountered, advance start to max(start, lastIndex + 1)."
    ],
    explanation: "As we iterate with right pointer, if character exists in map and its index >= left, we fast-forward left = map[char] + 1. Maximum length is updated at every step.",
    solution: "Map<char, int> seen. int left = 0, maxLen = 0. For int right = 0 to n-1: if seen contains s[right] and seen[s[right]] >= left: left = seen[s[right]] + 1. seen[s[right]] = right. maxLen = max(maxLen, right - left + 1). Return maxLen.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(min(N, AlphabetSize))",
    tags: ["Strings", "Sliding Window", "Hash Map", "Microsoft", "Amazon"],
    recommendedForRoles: ["Frontend Developer", "Software Engineer", "Full Stack Developer"],
    whyRecommended: "Classic sliding window interview question evaluating linear parsing and duplicate detection.",
    createdAt: "2025-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dsa-004",
    title: "3Sum Zero (Three Pointer Triplet Search)",
    question: "Given an integer array nums, return all unique triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.",
    type: "Coding",
    company: "Meta",
    role: "Software Engineer",
    round: "Coding Round",
    domain: "DSA",
    topic: "Arrays",
    subtopic: "Two Pointers",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Meta Technical Screening 2024",
    verified: true,
    testCases: [
      { input: "nums = [-1,0,1,2,-1,-4]", expectedOutput: "[[-1,-1,2],[-1,0,1]]" },
      { input: "nums = [0,1,1]", expectedOutput: "[]" }
    ],
    hints: [
      "Sorting the array first in O(N log N) makes duplicate elimination trivial.",
      "Fix one element nums[i] and run two pointers (left=i+1, right=n-1) to find complementary pairs."
    ],
    explanation: "Sort array. Loop i from 0 to n-3. Skip duplicates if nums[i] == nums[i-1]. Use two pointers left and right. If sum == 0, record triplet and skip duplicate adjacent values for both left and right. If sum < 0, left++; if sum > 0, right--.",
    solution: "Sort nums. For i = 0 to n-3: if i > 0 and nums[i] == nums[i-1] continue; left = i+1, right = n-1; while left < right: sum = nums[i] + nums[left] + nums[right]; if sum == 0: add [nums[i], nums[left], nums[right]]; while left < right and nums[left] == nums[left+1] left++; while left < right and nums[right] == nums[right-1] right--; left++; right--; else if sum < 0: left++; else: right--.",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(log N) for sorting",
    tags: ["Arrays", "Sorting", "Two Pointers", "Meta", "Amazon"],
    recommendedForRoles: ["Software Engineer", "Backend Developer"],
    whyRecommended: "Essential pattern for quadratic-to-linear subarray and pair reductions.",
    createdAt: "2025-01-20T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dsa-005",
    title: "Course Schedule (Cycle Detection in Directed Graph)",
    question: "There are numCourses courses labeled 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [a, b] indicates you must take course b first. Return true if you can finish all courses.",
    type: "Coding",
    company: "Uber",
    role: "Backend Developer",
    round: "Technical Round 2",
    domain: "DSA",
    topic: "Graphs",
    subtopic: "Topological Sort",
    difficulty: "Medium",
    sourceType: "Reported Question",
    source: "Uber SDE-2 Interview Experience Report",
    verified: true,
    testCases: [
      { input: "numCourses = 2, prerequisites = [[1,0]]", expectedOutput: "true" },
      { input: "numCourses = 2, prerequisites = [[1,0],[0,1]]", expectedOutput: "false" }
    ],
    hints: [
      "Can this problem be modeled as detecting a cycle in a directed graph?",
      "Use Kahn's algorithm (indegree counting with queue) or DFS cycle detection using 3-color states (unvisited, visiting, visited)."
    ],
    explanation: "If the directed dependency graph contains a cycle, deadlock occurs and courses cannot be finished. Kahn's Algorithm computes in-degrees for all nodes, pushes zero-indegree nodes into a queue, and decrements neighbors on dequeue. If the total dequeued nodes equals numCourses, no cycle exists.",
    solution: "Build adjacency list and inDegree array of size numCourses. Queue q. For each i in 0..numCourses-1: if inDegree[i] == 0 q.push(i). While q not empty: u = q.pop(); count++; for each v in adj[u]: inDegree[v]--; if inDegree[v] == 0 q.push(v). Return count == numCourses.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V + E)",
    tags: ["Graphs", "Topological Sort", "BFS", "Uber", "Google"],
    recommendedForRoles: ["Backend Developer", "Systems Engineer"],
    whyRecommended: "Validates dependency resolution and cycle detection algorithms used in build tools and task schedulers.",
    createdAt: "2025-02-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dsa-006",
    title: "Reverse a Linked List (Iterative & Recursive)",
    question: "Given the head of a singly linked list, reverse the list, and return the reversed list.",
    type: "Coding",
    company: "TCS",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "DSA",
    topic: "Linked List",
    subtopic: "Pointers",
    difficulty: "Easy",
    sourceType: "Verified Company Question",
    source: "TCS Digital Technical Drive 2025",
    verified: true,
    testCases: [
      { input: "head = [1,2,3,4,5]", expectedOutput: "[5,4,3,2,1]" },
      { input: "head = [1,2]", expectedOutput: "[2,1]" }
    ],
    hints: ["Maintain three pointers: prev, curr, and next.", "At each step, save curr.next, redirect curr.next = prev, then shift prev = curr and curr = next."],
    explanation: "Iterate through the list, dynamically repointing each node to the preceding node while caching the forward pointer to avoid orphan pointer leaks.",
    solution: "ListNode prev = null, curr = head; while (curr != null) { ListNode next = curr.next; curr.next = prev; prev = curr; curr = next; } return prev;",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    tags: ["Linked List", "Pointers", "TCS", "Infosys", "Wipro"],
    recommendedForRoles: ["Software Engineer", "Full Stack Developer"],
    whyRecommended: "Fundamental pointer manipulation benchmark in service and product entry-level screenings.",
    createdAt: "2025-01-10T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 2. DBMS (SQL, ACID, INDEXING, TRANSACTIONS) ───────────────────
  {
    id: "qb-dbms-001",
    title: "ACID Isolation Levels & Phantom Reads vs Non-Repeatable Reads",
    question: "Differentiate between Read Committed, Repeatable Read, and Serializable isolation levels. Explain what anomaly Repeatable Read prevents that Read Committed allows.",
    type: "Conceptual",
    company: "Goldman Sachs",
    role: "Software Engineer",
    round: "Technical Round 2",
    domain: "DBMS",
    topic: "Transactions",
    subtopic: "ACID Isolation",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Goldman Sachs Systems & DB Architecture Round",
    verified: true,
    hints: [
      "Consider what happens when Transaction A reads row X twice, while Transaction B commits an update in between.",
      "Consider range queries vs individual row updates (Phantom vs Non-Repeatable reads)."
    ],
    explanation: "Read Committed acquires short-lived read locks or evaluates snapshot at statement start; if another transaction commits an update to row X mid-transaction, reading X again produces the new value (Non-Repeatable Read). Repeatable Read creates a transaction-level snapshot at the first read, guaranteeing identical values on repeated reads. Serializable prevents Phantom Reads by serializing execution order via range locks or strict serialization checking.",
    solution: "1. Read Committed: Guarantees no dirty reads (uncommitted data never read). Allows non-repeatable read.\n2. Repeatable Read: Uses snapshot isolation (MVCC) or shared locks held until transaction end. Guarantees same row reads return same values.\n3. Serializable: Prevents phantom reads (new rows appearing in range queries) using Next-Key Locks or serializable snapshot isolation (SSI).",
    tags: ["DBMS", "ACID", "Concurrency", "Goldman Sachs", "Razorpay"],
    recommendedForRoles: ["Backend Developer", "Data Engineer"],
    whyRecommended: "Essential for financial ledgers, transactional consistency, and concurrent high-load database architecture.",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dbms-002",
    title: "Department Top 3 Salaries using SQL Window Functions",
    question: "Write an SQL query to find the employees who earn the top 3 unique salaries in each of the department. An employee is in top 3 if their salary ranks 1, 2, or 3 among distinct salaries in their department.",
    type: "SQL",
    company: "Amazon",
    role: "Data Analyst",
    round: "Online Assessment",
    domain: "DBMS",
    topic: "SQL",
    subtopic: "Window Functions",
    difficulty: "Medium",
    sourceType: "Reported Question",
    source: "Amazon Data Engineering OA",
    verified: true,
    codeSnippet: `SELECT d.name AS Department, e.name AS Employee, e.salary AS Salary\nFROM (\n  SELECT departmentId, name, salary,\n         DENSE_RANK() OVER (PARTITION BY departmentId ORDER BY salary DESC) as rnk\n  FROM Employee\n) e\nJOIN Department d ON e.departmentId = d.id\nWHERE e.rnk <= 3;`,
    hints: [
      "Why use DENSE_RANK() instead of RANK() or ROW_NUMBER()?",
      "DENSE_RANK handles ties without skipping rank numbers (1, 2, 2, 3)."
    ],
    explanation: "DENSE_RANK() assigns consecutive rank values to unique salaries within each department partition. If two employees share the top salary, they both get rank 1, and the next highest salary is rank 2.",
    solution: "Use a Common Table Expression (CTE) or subquery with DENSE_RANK() OVER (PARTITION BY departmentId ORDER BY salary DESC) AS rnk. Then filter WHERE rnk <= 3 and join with Department table to fetch department name.",
    tags: ["SQL", "Window Functions", "DENSE_RANK", "Amazon", "Flipkart"],
    recommendedForRoles: ["Data Analyst", "Backend Developer", "Data Scientist"],
    whyRecommended: "Tests advanced SQL aggregation and ranking logic critical for analytics pipelines.",
    createdAt: "2025-01-25T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-dbms-003",
    title: "Database Indexing: B+ Tree vs Hash Index Mechanics",
    question: "Why do relational databases like PostgreSQL and MySQL InnoDB use B+ Trees instead of Hash Maps or Binary Search Trees for table indexing?",
    type: "Conceptual",
    company: "Flipkart",
    role: "Backend Developer",
    round: "Technical Round 1",
    domain: "DBMS",
    topic: "Indexing",
    subtopic: "B+ Tree",
    difficulty: "Medium",
    sourceType: "Community-Sourced Question",
    source: "Flipkart Backend Engineering Panel",
    verified: true,
    hints: [
      "Think about range queries (e.g. WHERE age BETWEEN 20 AND 30). How would a Hash Index handle that?",
      "Think about disk block reads: how does a B+ Tree's wide branching factor (high fan-out) reduce I/O seeks?"
    ],
    explanation: "Hash indexes offer O(1) for point lookups (WHERE id = 5) but cannot do range scans (BETWEEN, <, >) without full table scans. Binary search trees have shallow fan-out causing deep trees and multiple disk I/O operations. B+ Trees have large fan-out (hundreds of keys per 4KB/16KB page), keeping depth to 3-4 levels for billions of rows. All leaf nodes are linked sequentially in a doubly linked list, making range scans blazing fast.",
    solution: "1. Range queries: B+ Tree leaf nodes form a sorted linked list; once the start key is found in O(log N), range traversal is O(K) sequential disk reads.\n2. Disk I/O efficiency: High fan-out fits hundreds of child pointers per page, minimizing disk block fetches to <= 3-4 I/Os.\n3. Predictable performance: All leaf nodes reside at equal depth, guaranteeing uniform O(log N) lookup time.",
    tags: ["DBMS", "Indexing", "B+ Tree", "MySQL", "Postgres"],
    recommendedForRoles: ["Backend Developer", "Systems Engineer"],
    whyRecommended: "Fundamental database architecture knowledge required to prevent catastrophic production query regressions.",
    createdAt: "2025-02-18T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 3. OOP (DESIGN PRINCIPLES, SOLID, PATTERNS) ────────────────────
  {
    id: "qb-oop-001",
    title: "SOLID Principles in Production Architecture",
    question: "Explain the Liskov Substitution Principle (LSP) and Interface Segregation Principle (ISP) with a concrete real-world refactoring example.",
    type: "Conceptual",
    company: "Microsoft",
    role: "Software Engineer",
    round: "Technical Round 2",
    domain: "OOP",
    topic: "SOLID",
    subtopic: "Liskov & Interface Segregation",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Microsoft SDE Interview Matrix",
    verified: true,
    hints: ["Classic LSP violation: Square inheriting from Rectangle with setters.", "ISP: A fat interface with 20 methods forcing client classes to write empty stubs."],
    explanation: "LSP: Subtypes must be substitutable for base types without breaking program behavior. ISP: Clients should not be forced to depend upon interfaces they do not use.",
    solution: "LSP violation: class Rectangle { setWidth(w); setHeight(h); } class Square extends Rectangle { setWidth(w) { this.w = this.h = w; } }. A function resize(Rectangle r) { r.setWidth(5); r.setHeight(4); assert(r.area() == 20); } fails for Square. Refactor by separating into Shape interface. ISP: Instead of interface Worker { work(); eat(); sleep(); }, split into Workable and Feedable so robot workers do not implement empty eat() methods.",
    tags: ["OOP", "SOLID", "Architecture", "Microsoft", "Oracle"],
    recommendedForRoles: ["Full Stack Developer", "Backend Developer", "Software Engineer"],
    whyRecommended: "Validates code maintainability, decoupling patterns, and production system extensibility.",
    createdAt: "2025-01-30T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-oop-002",
    title: "Thread-Safe Singleton Pattern (Double-Checked Locking)",
    question: "Write a thread-safe Singleton class in Java or C++. Explain why the 'volatile' keyword is mandatory in Double-Checked Locking.",
    type: "Coding",
    company: "Adobe",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "OOP",
    topic: "Design Patterns",
    subtopic: "Singleton Pattern",
    difficulty: "Medium",
    sourceType: "Reported Question",
    source: "Adobe Engineering Drive",
    verified: true,
    codeSnippet: `public class DatabaseConnection {\n  private static volatile DatabaseConnection instance;\n  private DatabaseConnection() {}\n\n  public static DatabaseConnection getInstance() {\n    if (instance == null) {\n      synchronized (DatabaseConnection.class) {\n        if (instance == null) {\n          instance = new DatabaseConnection();\n        }\n      }\n    }\n    return instance;\n  }\n}`,
    hints: ["What does CPU instruction reordering do during object creation: allocation -> initialization -> assignment?"],
    explanation: "Without volatile, the JVM/CPU can reorder instructions during new Object(): allocating memory, assigning reference to instance, and then executing constructor. Another thread checking instance != null might access an uninitialized object!",
    solution: "Double-checked locking checks instance == null twice. The volatile keyword prevents CPU instruction reordering and establishes a happens-before memory barrier, guaranteeing that memory allocation and constructor initialization complete before the reference is published.",
    tags: ["OOP", "Design Patterns", "Concurrency", "Java", "Adobe"],
    recommendedForRoles: ["Software Engineer", "Backend Developer"],
    whyRecommended: "Essential concurrency and memory model interview check for object lifecycle management.",
    createdAt: "2025-02-12T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 4. OPERATING SYSTEMS (CONCURRENCY, MEMORY, DEADLOCKS) ──────────
  {
    id: "qb-os-001",
    title: "Virtual Memory, Page Faults & Translation Lookaside Buffer (TLB)",
    question: "Walk through the hardware and OS steps that occur when a CPU instruction accesses an address that results in a Page Fault.",
    type: "Conceptual",
    company: "Qualcomm",
    role: "Systems Engineer",
    round: "Technical Round 1",
    domain: "Operating Systems",
    topic: "Memory Management",
    subtopic: "Paging & TLB",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Qualcomm Systems & Kernel Screening",
    verified: true,
    hints: ["Check MMU -> TLB miss -> Page table walk -> Present bit 0 -> Trap interrupt to kernel."],
    explanation: "When an instruction requests virtual address V, MMU probes TLB. On miss, it consults page tables. If the present bit is 0, the CPU traps to the kernel Page Fault Handler. The OS checks the VMA: if valid, it finds an empty physical frame (or evicts via LRU), issues disk I/O, updates page table and TLB, and resumes the faulting instruction.",
    solution: "1. MMU queries TLB: miss.\n2. MMU walks page table: Valid bit = 0.\n3. Hardware raises Page Fault Exception (Interrupt 14 on x86).\n4. CPU switches to Kernel Mode, saves register state.\n5. OS verifies address validity against process memory descriptor.\n6. OS allocates physical frame (running page replacement if full).\n7. Disk controller reads 4KB page from swap/backing file.\n8. OS writes physical address into page table entry and marks valid=1.\n9. TLB is updated/invalidated.\n10. Context restored; instruction re-executed.",
    tags: ["OS", "Memory", "Paging", "Qualcomm", "Intel", "Apple"],
    recommendedForRoles: ["Systems Engineer", "Embedded Software Engineer"],
    whyRecommended: "Evaluates low-level understanding of memory hierarchy, OS paging, and kernel-user space transitions.",
    createdAt: "2025-01-28T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-os-002",
    title: "Deadlock Conditions & Banker's Algorithm",
    question: "State the four Coffman conditions necessary for a deadlock. How does Banker's Algorithm ensure safety against deadlock?",
    type: "Conceptual",
    company: "NVIDIA",
    role: "Software Engineer",
    round: "Technical Round 2",
    domain: "Operating Systems",
    topic: "Deadlocks",
    subtopic: "Coffman Conditions",
    difficulty: "Medium",
    sourceType: "Reported Question",
    source: "NVIDIA Core Architecture Interview",
    verified: true,
    hints: ["Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait."],
    explanation: "Deadlock requires all 4 Coffman conditions simultaneously. Breaking any one condition prevents deadlock. Banker's Algorithm tests for safety by simulating resource allocation for maximum possible claims to ensure a safe sequence exists.",
    solution: "Four Coffman Conditions:\n1. Mutual Exclusion: Resources non-shareable.\n2. Hold and Wait: A process holds resources while waiting for more.\n3. No Preemption: Resources cannot be forcibly seized.\n4. Circular Wait: P0 waits for P1, P1 waits for P2... Pn waits for P0.\nBanker's Algorithm: Maintains Available, Max, Allocation, Need matrices. When request arrives, it hypothetically allocates resources and executes Safety Algorithm: finds a process whose Need <= Available, assumes it finishes and releases resources, repeating until all processes finish (Safe State). If no safe sequence exists, request is rejected.",
    tags: ["OS", "Deadlock", "Concurrency", "NVIDIA", "Qualcomm"],
    recommendedForRoles: ["Systems Engineer", "Software Engineer"],
    whyRecommended: "Essential concurrency and resource scheduling theory evaluated in core systems engineering.",
    createdAt: "2025-02-22T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 5. COMPUTER NETWORKS (TCP/IP, HTTP, DNS, SECURITY) ─────────────
  {
    id: "qb-cn-001",
    title: "TCP 3-Way Handshake & TIME_WAIT State Management",
    question: "Explain the TCP 3-way handshake and 4-way termination. Why does the active closer transition into the TIME_WAIT state for 2*MSL?",
    type: "Conceptual",
    company: "Cisco",
    role: "Cloud Engineer",
    round: "Technical Round 1",
    domain: "Computer Networks",
    topic: "Transport Layer",
    subtopic: "TCP Handshake",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Cisco Cloud Networking Drive",
    verified: true,
    hints: ["SYN -> SYN-ACK -> ACK. What happens if the final ACK is lost? What happens to delayed stray packets in transit?"],
    explanation: "Handshake synchronizes initial sequence numbers (ISN). TIME_WAIT lasts 2 * Maximum Segment Lifetime (typically 1-2 minutes). It ensures that if the final ACK was dropped in the network, the remote host's retransmitted FIN can be acknowledged properly rather than receiving a connection reset (RST), and ensures wandering duplicate packets from prior sessions die out before a new connection reuses the same port.",
    solution: "1. Handshake: Client -> SYN(seq=x) -> Server -> SYN(seq=y)+ACK(ack=x+1) -> Client -> ACK(ack=y+1).\n2. Teardown: Client -> FIN -> Server -> ACK -> Server -> FIN -> Client -> ACK -> TIME_WAIT.\n3. TIME_WAIT purpose: 1) Allows final ACK retransmission if dropped; 2) Drains in-flight duplicate segments to prevent socket collision upon port reuse.",
    tags: ["Computer Networks", "TCP/IP", "Sockets", "Cisco", "Cloudflare"],
    recommendedForRoles: ["Backend Developer", "DevOps Engineer", "Cloud Engineer"],
    whyRecommended: "Crucial for debugging socket exhaustion, connection latency, and distributed RPC reliability.",
    createdAt: "2025-01-18T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-cn-002",
    title: "DNS Resolution Lifecycle & What Happens When You Type google.com",
    question: "Walk through the complete networking sequence that occurs from the moment a user presses Enter on 'https://google.com' until the HTML begins rendering in the browser.",
    type: "Conceptual",
    company: "Google",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "Computer Networks",
    topic: "Application Layer",
    subtopic: "DNS & HTTP/TLS",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Google SWE Onsite Standard Question",
    verified: true,
    hints: ["Browser cache -> OS cache -> Resolver -> Root DNS -> TLD (.com) -> Authoritative -> TCP handshake -> TLS handshake -> HTTP GET -> DOM parse."],
    explanation: "1. Browser checks cache, hosts file, local resolver. 2. DNS query recursively walks Root (.), TLD (.com), and Authoritative nameservers. 3. ARP resolves IP to MAC if in local subnet. 4. TCP 3-way handshake over port 443. 5. TLS 1.3 handshake negotiates cipher suite, verifies certificate, establishes symmetric session key. 6. HTTP GET request sent. 7. Server streams response. 8. Browser renders DOM/CSSOM.",
    solution: "Detailed 8-stage breakdown: DNS hierarchical resolution -> TCP connection setup -> TLS cryptographic session negotiation -> HTTP request streaming -> Server reverse proxy routing -> Client HTML tokenization, critical render path, script hydration.",
    tags: ["Computer Networks", "DNS", "HTTP", "TLS", "Google"],
    recommendedForRoles: ["Full Stack Developer", "Backend Developer", "Frontend Developer"],
    whyRecommended: "Universal end-to-end networking question testing holistic software lifecycle understanding.",
    createdAt: "2025-02-05T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 6. AI / ML & GENERATIVE AI ─────────────────────────────────────
  {
    id: "qb-aiml-001",
    title: "Bias-Variance Tradeoff, L1 vs L2 Regularization & Sparsity",
    question: "Explain why L1 (Lasso) regularization leads to sparse weight vectors (exact zeros) while L2 (Ridge) shrinks weights smoothly without zeros.",
    type: "Conceptual",
    company: "Apple",
    role: "ML Engineer",
    round: "Technical Round 2",
    domain: "AI / ML",
    topic: "Regularization",
    subtopic: "L1 vs L2 Geometry",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Apple Machine Learning Research Screening",
    verified: true,
    hints: ["Geometric contour intersections: Diamond (L1) vs Sphere (L2). Constant gradient derivative vs proportional gradient."],
    explanation: "L1 norm contour forms a hyper-diamond with sharp corners on coordinate axes. Contours of the loss function intersect corners on axes with high probability, setting coordinates to exactly 0. L2 contour is spherical, touching loss ellipses smoothly without hitting zero coordinates.",
    solution: "1. Geometric view: L1 constraint region |w1| + |w2| <= C has sharp corners on axes. Error ellipses touch corners where coordinates equal zero (sparsity). L2 w1^2 + w2^2 <= C is circular/spherical with no points of discontinuity.\n2. Derivative view: L1 gradient penalty is +/- lambda (constant pull to zero). L2 penalty is 2 * lambda * w (shrinks asymptotically slower as w approaches zero).",
    tags: ["AI/ML", "Regularization", "Math", "Apple", "Google"],
    recommendedForRoles: ["ML Engineer", "Data Scientist"],
    whyRecommended: "Directly tests statistical machine learning fundamentals, feature sparsity, and loss geometry.",
    createdAt: "2025-01-22T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-genai-001",
    title: "Retrieval-Augmented Generation (RAG) Architecture & Chunking Strategies",
    question: "How do you design an enterprise RAG pipeline that minimizes hallucination, handles dense vs sparse hybrid search, and avoids the 'Lost in the Middle' problem?",
    type: "System Design",
    company: "Microsoft",
    role: "AI Engineer",
    round: "System Design",
    domain: "Generative AI",
    topic: "RAG Systems",
    subtopic: "Hybrid Search & Re-ranking",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Microsoft Azure AI Architecture Interview",
    verified: true,
    hints: ["Hybrid search combines BM25 keyword matching with dense vector embeddings via Reciprocal Rank Fusion (RRF). Cross-encoder re-ranking."],
    explanation: "An enterprise RAG pipeline uses semantic chunking based on header boundaries and sentence structure. Ingestion computes both BM25 sparse vectors and dense embeddings (e.g., text-embedding-3). Queries execute hybrid search combined via Reciprocal Rank Fusion (RRF). Top 50 results pass to a Cross-Encoder Re-ranker to pick top 5. The prompt is structured with citation anchors and instructions to cite evidence IDs strictly. Crucial chunks are placed at the beginning and end of the context window to overcome attention decay in the middle.",
    solution: "1. Semantic Chunking (512 tokens, 10% overlap).\n2. Hybrid Search (Dense vectors + BM25 sparse with RRF).\n3. Re-ranking: Cross-encoder (Cohere Rerank / BGE-reranker) extracts top 5.\n4. Context Arrangement: Place highest-scored chunks at prompt boundaries.\n5. Guardrails: Self-critique / Ragas evaluation (Faithfulness, Relevance).",
    tags: ["Generative AI", "RAG", "LLM", "Vector DB", "Microsoft"],
    recommendedForRoles: ["AI Engineer", "ML Engineer", "Backend Developer"],
    whyRecommended: "Targeted evaluation for AI/ML and GenAI roles; verifies production retrieval and context structuring.",
    createdAt: "2025-02-14T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 7. HR / BEHAVIORAL (STAR METHOD, CONFLICT, LP) ────────────────
  {
    id: "qb-hr-001",
    title: "Resolving Engineering Disagreements & Amazon LP (Disagree and Commit)",
    question: "Describe a time when you strongly disagreed with a technical decision made by your peer or lead. How did you present your case, and what was the outcome?",
    type: "HR / Behavioral",
    company: "Amazon",
    role: "SDE",
    round: "Behavioral",
    domain: "HR / Behavioral",
    topic: "Leadership Principles",
    subtopic: "Have Backbone; Disagree and Commit",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Amazon Bar Raiser Behavioral Rubric",
    verified: true,
    hints: ["Use STAR format: Situation, Task, Action, Result. Never make it a personal attack. Focus on empirical benchmarks."],
    explanation: "Amazon leaders must respectfully challenge decisions when they disagree, even when doing so is uncomfortable. Once a decision is determined, they commit wholly. The story should highlight empirical evidence gathering and graceful alignment.",
    solution: "Structure your response:\n- Situation: Lead wanted MongoDB; you foresaw ACID inconsistency for payment ledger.\n- Task: Protect financial data integrity without blocking project milestones.\n- Action: Built reproducible load-test script exposing race-condition double-spend; presented PostgreSQL benchmark with serializable isolation.\n- Result: Team adopted PostgreSQL; ledger launched with zero financial discrepancies. Emphasize that if lead had overruled, you would have written application-level safeguards and supported the decision fully.",
    tags: ["Behavioral", "STAR", "Leadership Principles", "Amazon"],
    recommendedForRoles: ["Software Engineer", "Engineering Manager", "Product Manager"],
    whyRecommended: "Tests professional maturity, empirical argumentation, and collaborative team alignment.",
    createdAt: "2025-01-05T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 8. APTITUDE (QUANTITATIVE & LOGICAL) ───────────────────────────
  {
    id: "qb-apt-001",
    title: "Work & Time with Alternating Pipe Efficiencies",
    question: "Pipe A can fill a tank in 12 hours, Pipe B in 15 hours, and Pipe C can empty it in 20 hours. If all three pipes are opened together, how long will it take to fill the tank completely?",
    type: "Aptitude",
    company: "TCS",
    role: "Software Engineer",
    round: "Aptitude",
    domain: "Aptitude",
    topic: "Quantitative",
    subtopic: "Pipes & Cisterns",
    difficulty: "Easy",
    sourceType: "Verified Company Question",
    source: "TCS iON NQT Campus Paper",
    verified: true,
    hints: ["Find the LCM of 12, 15, and 20 to establish total capacity in units."],
    explanation: "Let capacity = LCM(12, 15, 20) = 60 units. Rate of A = +5 units/hr. Rate of B = +4 units/hr. Rate of C = -3 units/hr. Net rate = 5 + 4 - 3 = 6 units/hr. Total time = 60 / 6 = 10 hours.",
    solution: "LCM(12, 15, 20) = 60 units.\nEfficiency of Pipe A = 60/12 = +5\nEfficiency of Pipe B = 60/15 = +4\nEfficiency of Pipe C = 60/20 = -3\nCombined rate = 5 + 4 - 3 = 6 units/hour.\nTime required = 60 / 6 = 10 hours.",
    tags: ["Aptitude", "Quantitative", "TCS", "Infosys", "Wipro"],
    recommendedForRoles: ["Software Engineer", "Campus Placement Candidate"],
    whyRecommended: "Standard first-round campus elimination filter question testing unit-rate arithmetic under timed conditions.",
    createdAt: "2025-01-08T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── 9. SYSTEM DESIGN (HIGH CONCURRENCY, DISTRIBUTED ARCHITECTURE) ──
  {
    id: "qb-sys-001",
    title: "Design a High-Throughput Distributed Rate Limiter",
    question: "Design an API Rate Limiter handling 100,000 requests/sec per client tier. Compare Token Bucket vs Sliding Window Log vs Sliding Window Counter, and address Redis concurrency race conditions.",
    type: "System Design",
    company: "Uber",
    role: "Backend Developer",
    round: "System Design",
    domain: "System Design",
    topic: "Distributed Systems",
    subtopic: "Rate Limiting",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Uber Systems Engineering Screening",
    verified: true,
    hints: ["How do you prevent check-then-set race conditions in Redis? Atomic Lua scripts."],
    explanation: "Sliding Window Counter algorithm using Redis Lua scripts prevents race conditions between read and increment. Memory footprint is minimal compared to storing full timestamp logs.",
    solution: "1. Algorithm: Sliding Window Counter.\n2. In-memory data store: Redis cluster partitioned by client ID.\n3. Atomicity: Redis Lua script executes ZREMRANGEBYSCORE, ZCARD, ZADD, and EXPIRE in a single atomic roundtrip.\n4. High availability: If Redis fails, API gateway falls back to local in-memory Token Bucket with circuit breakers to prevent traffic blackouts.",
    timeComplexity: "O(1) amortized",
    spaceComplexity: "O(N) where N is active client count",
    tags: ["System Design", "Redis", "Distributed Systems", "Uber", "Stripe"],
    recommendedForRoles: ["Backend Developer", "System Architect"],
    whyRecommended: "Core FAANG/Unicorn system design question evaluating distributed locks, latency budgets, and fault tolerance.",
    createdAt: "2025-02-16T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  }
];
