import { QuestionItem } from "./question-bank-types";
import { ALL_QUESTION_BANK_ITEMS } from "./question-bank-data";

export const EXPANDED_PLACEMENT_QUESTIONS: QuestionItem[] = [
  ...ALL_QUESTION_BANK_ITEMS,

  // ─── GOOGLE CODING & SYSTEM ROUNDS ─────────────────────────────────
  {
    id: "qb-goog-001",
    title: "Median of Two Sorted Arrays (Logarithmic Binary Search)",
    question: "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays in O(log (m+n)) runtime.",
    type: "Coding",
    company: "Google",
    role: "Software Engineer",
    round: "Technical Round 2",
    domain: "DSA",
    topic: "Arrays",
    subtopic: "Binary Search",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Google Onsite Interview 2024",
    verified: true,
    testCases: [
      { input: "nums1 = [1,3], nums2 = [2]", expectedOutput: "2.0" },
      { input: "nums1 = [1,2], nums2 = [3,4]", expectedOutput: "2.5" }
    ],
    hints: [
      "Binary search on the partition of the smaller array.",
      "Partitioning ensures left half and right half contain equal elements."
    ],
    explanation: "We partition nums1 and nums2 such that left partition elements <= right partition elements. Because both arrays are sorted, binary search on partitionX in [0, m] converges in O(log(min(m, n))).",
    solution: "Binary search on partitionX. Calculate partitionY = (m + n + 1) / 2 - partitionX. Check maxLeftX <= minRightY && maxLeftY <= minRightX. If total length is even: (max(maxLeftX, maxLeftY) + min(minRightX, minRightY)) / 2.0; else max(maxLeftX, maxLeftY).",
    timeComplexity: "O(log(min(m, n)))",
    spaceComplexity: "O(1)",
    tags: ["Arrays", "Binary Search", "Google"],
    recommendedForRoles: ["Software Engineer", "AI/ML Engineer"],
    whyRecommended: "Tests logarithmic binary search partitioning under extreme edge cases.",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-goog-002",
    title: "Word Break using Dynamic Programming and Trie",
    question: "Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.",
    type: "Coding",
    company: "Google",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "DSA",
    topic: "Dynamic Programming",
    subtopic: "Strings & Trie",
    difficulty: "Medium",
    sourceType: "Reported Question",
    source: "Google Campus Drive Report",
    verified: true,
    testCases: [
      { input: "s = 'leetcode', wordDict = ['leet','code']", expectedOutput: "true" },
      { input: "s = 'applepenapple', wordDict = ['apple','pen']", expectedOutput: "true" }
    ],
    hints: ["Let dp[i] represent whether s[0..i] can be segmented.", "dp[i] is true if any dp[j] is true and s[j..i] is in wordDict."],
    explanation: "1D boolean DP array where dp[i] indicates whether the prefix of length i can be formed using dictionary words.",
    solution: "Set<String> dict = new HashSet<>(wordDict); boolean[] dp = new boolean[s.length() + 1]; dp[0] = true; for (int i = 1; i <= s.length(); i++) { for (int j = 0; j < i; j++) { if (dp[j] && dict.contains(s.substring(j, i))) { dp[i] = true; break; } } } return dp[s.length()];",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(N)",
    tags: ["Dynamic Programming", "Strings", "Google"],
    recommendedForRoles: ["Software Engineer", "Full Stack Developer"],
    whyRecommended: "Classic dynamic programming state formulation on string substrings.",
    createdAt: "2025-01-05T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── MICROSOFT CODING & CS FUNDAMENTALS ─────────────────────────────
  {
    id: "qb-msft-001",
    title: "Lowest Common Ancestor in a Binary Tree",
    question: "Given a binary tree, find the lowest common ancestor (LCA) of two given nodes p and q.",
    type: "Coding",
    company: "Microsoft",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "DSA",
    topic: "Trees",
    subtopic: "Binary Tree Traversal",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Microsoft Onsite Interview",
    verified: true,
    testCases: [
      { input: "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1", expectedOutput: "3" },
      { input: "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 4", expectedOutput: "5" }
    ],
    hints: ["Traverse recursively. If current node matches p or q, return current node.", "If both left and right recursive calls return non-null, current node is the LCA."],
    explanation: "A post-order DFS traversal checks both subtrees. If a node finds p in its left child and q in its right child, it must be the Lowest Common Ancestor.",
    solution: "TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) { if (root == null || root == p || root == q) return root; TreeNode left = lowestCommonAncestor(root.left, p, q); TreeNode right = lowestCommonAncestor(root.right, p, q); if (left != null && right != null) return root; return left != null ? left : right; }",
    timeComplexity: "O(N)",
    spaceComplexity: "O(H) recursion stack",
    tags: ["Trees", "Recursion", "Microsoft", "Amazon"],
    recommendedForRoles: ["Software Engineer", "Backend Developer"],
    whyRecommended: "Evaluates recursive tree reasoning and subtree post-order synthesis.",
    createdAt: "2025-01-12T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-msft-002",
    title: "Process vs Thread & Thread Synchronization Primitives",
    question: "Compare process-level isolation vs thread-level memory sharing. How do Mutexes, Semaphores, and Spinlocks differ in CPU context-switching overhead?",
    type: "Conceptual",
    company: "Microsoft",
    role: "Cloud Engineer",
    round: "Technical Round 2",
    domain: "Operating Systems",
    topic: "Processes & Threads",
    subtopic: "Synchronization",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Microsoft Azure Engineering Screening",
    verified: true,
    hints: ["Spinlock burns CPU cycles in a tight loop; Mutex puts thread to sleep.", "Processes have separate virtual address spaces (MMU page tables); threads share heap, code, data."],
    explanation: "Processes have distinct MMU address spaces and require IPC (pipes, sockets, shared memory) with high context-switch cost (flushing TLB). Threads share memory space and have lighter context switching. Spinlocks are ideal for very short critical sections where thread sleep/wakeup latency exceeds spin latency.",
    solution: "1. Process: Isolated memory, requires IPC, high context switch cost (TLB flush).\n2. Thread: Shared heap/static memory, private stack/registers, low context switch.\n3. Mutex: Binary mutual exclusion; sleeps waiting thread.\n4. Semaphore: Counting semaphore allows N concurrent accessors.\n5. Spinlock: Busy-waits (spins) on atomic test-and-set instruction; avoids context switch penalty for ultra-fast locks.",
    tags: ["Operating Systems", "Threads", "Concurrency", "Microsoft"],
    recommendedForRoles: ["Backend Developer", "Cloud Engineer", "Systems Engineer"],
    whyRecommended: "Essential multi-threading and OS memory model understanding for cloud backends.",
    createdAt: "2025-01-24T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── META / FACEBOOK CODING & SYSTEM DESIGN ─────────────────────────
  {
    id: "qb-meta-001",
    title: "Valid Palindrome II (At Most One Character Deletion)",
    question: "Given a string s, return true if the s can be palindrome after deleting at most one character from it.",
    type: "Coding",
    company: "Meta",
    role: "Software Engineer",
    round: "Coding Round",
    domain: "DSA",
    topic: "Strings",
    subtopic: "Two Pointers",
    difficulty: "Easy",
    sourceType: "Verified Company Question",
    source: "Meta SDE Screening Interview",
    verified: true,
    testCases: [
      { input: "s = 'aba'", expectedOutput: "true" },
      { input: "s = 'abca'", expectedOutput: "true" },
      { input: "s = 'abc'", expectedOutput: "false" }
    ],
    hints: ["Use two pointers from left and right. When characters mismatch, check if s[left+1..right] OR s[left..right-1] is a palindrome."],
    explanation: "Two pointers check for symmetry. On the first mismatch at left and right, check if skipping left or skipping right yields a valid palindrome.",
    solution: "boolean validPalindrome(String s) { int left = 0, right = s.length() - 1; while (left < right) { if (s.charAt(left) != s.charAt(right)) { return isPalindrome(s, left + 1, right) || isPalindrome(s, left, right - 1); } left++; right--; } return true; }",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    tags: ["Strings", "Two Pointers", "Meta"],
    recommendedForRoles: ["Software Engineer", "Frontend Developer"],
    whyRecommended: "High frequency Meta phone screen question testing string pointer manipulation.",
    createdAt: "2025-02-02T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── FLIPKART & E-COMMERCE HIGH CONCURRENCY ─────────────────────────
  {
    id: "qb-flip-001",
    title: "Flash Sale Inventory Concurrency & Optimistic vs Pessimistic Locking",
    question: "During a flash sale with 1,000 iPhone units and 100,000 concurrent checkout requests, how do you prevent overselling while maintaining sub-50ms latency?",
    type: "System Design",
    company: "Flipkart",
    role: "Backend Developer",
    round: "Technical Round 2",
    domain: "System Design",
    topic: "Distributed Systems",
    subtopic: "Inventory Concurrency",
    difficulty: "Hard",
    sourceType: "Reported Question",
    source: "Flipkart Big Billion Days Architecture Round",
    verified: true,
    hints: ["Database row-level locks (SELECT ... FOR UPDATE) bottleneck at 100k req/s.", "Use in-memory Redis DECR with Lua script and asynchronous DB settlement via Kafka."],
    explanation: "Direct relational database locking collapses under 100k req/s. Instead, maintain inventory in Redis with atomic DECR. Only successful decrements receive a signed order token and publish to Kafka for durable database persistence.",
    solution: "1. Redis atomic decrement (Lua script) checks stock > 0 and decrements in single cycle.\n2. When stock reaches 0, fast-fail subsequent requests instantly (zero DB load).\n3. Successful requests push to Kafka order topic.\n4. Asynchronous worker pool consumes topic and updates PostgreSQL with idempotent transactions.",
    tags: ["System Design", "Redis", "Kafka", "Flipkart", "High Concurrency"],
    recommendedForRoles: ["Backend Developer", "System Architect"],
    whyRecommended: "Evaluates production e-commerce architecture and transactional inventory controls.",
    createdAt: "2025-02-19T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── TCS / INFOSYS / WIPRO CAMPUS RECRUITMENT ───────────────────────
  {
    id: "qb-tcs-001",
    title: "Find the Second Highest Salary in SQL",
    question: "Write an SQL query to report the second highest salary from the Employee table. If there is no second highest salary, return null.",
    type: "SQL",
    company: "TCS",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "DBMS",
    topic: "SQL",
    subtopic: "Subqueries & Aggregations",
    difficulty: "Easy",
    sourceType: "Verified Company Question",
    source: "TCS Digital Technical Screening",
    verified: true,
    codeSnippet: `SELECT MAX(salary) AS SecondHighestSalary\nFROM Employee\nWHERE salary < (SELECT MAX(salary) FROM Employee);`,
    hints: ["Filter salaries that are strictly less than the overall maximum salary."],
    explanation: "A correlated subquery finds the maximum salary strictly less than the global maximum, returning null if only one distinct salary exists.",
    solution: "SELECT (SELECT DISTINCT salary FROM Employee ORDER BY salary DESC LIMIT 1 OFFSET 1) AS SecondHighestSalary; or SELECT MAX(salary) AS SecondHighestSalary FROM Employee WHERE salary < (SELECT MAX(salary) FROM Employee);",
    tags: ["SQL", "DBMS", "TCS", "Infosys"],
    recommendedForRoles: ["Software Engineer", "Data Analyst"],
    whyRecommended: "Universal campus recruitment SQL query evaluating nested subqueries and NULL handling.",
    createdAt: "2025-01-08T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-infy-001",
    title: "Object-Oriented Programming: Abstract Class vs Interface",
    question: "Explain the architectural and syntactic differences between an Abstract Class and an Interface in Java/C++. When should you choose one over the other?",
    type: "Conceptual",
    company: "Infosys",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "OOP",
    topic: "Design Principles",
    subtopic: "Abstraction",
    difficulty: "Easy",
    sourceType: "Verified Company Question",
    source: "Infosys DSE Technical Round",
    verified: true,
    hints: ["Can an interface hold state (instance variables)? Can a class inherit multiple abstract classes?"],
    explanation: "An abstract class represents an 'is-a' relationship and can maintain state (instance variables) and constructors. An interface defines a 'can-do' contract allowing multiple inheritance of types.",
    solution: "1. Abstract Class: Supports instance variables, constructors, partial implementation, single inheritance.\n2. Interface: Defines public API contract, default/static methods in Java 8+, supports multiple inheritance of interface types.\n3. Choose Abstract Class when creating related classes sharing code/state. Choose Interface to define common behavior across unrelated classes (e.g. Comparable, Serializable).",
    tags: ["OOP", "Java", "Abstraction", "Infosys", "TCS"],
    recommendedForRoles: ["Software Engineer", "Full Stack Developer"],
    whyRecommended: "High frequency campus placement OOP question testing foundational design patterns.",
    createdAt: "2025-01-14T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── QUALCOMM & HARDWARE SYSTEMS ────────────────────────────────────
  {
    id: "qb-qual-001",
    title: "C++ Smart Pointers & Memory Leak Prevention",
    question: "Differentiate between std::unique_ptr, std::shared_ptr, and std::weak_ptr. How does std::weak_ptr resolve circular reference memory leaks?",
    type: "Conceptual",
    company: "Qualcomm",
    role: "Systems Engineer",
    round: "Technical Round 2",
    domain: "Programming",
    topic: "C++",
    subtopic: "Smart Pointers & RAII",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Qualcomm Modem Software Screening",
    verified: true,
    hints: ["Reference counting: when two shared_ptrs point to each other, ref count never drops to zero.", "weak_ptr observes object without incrementing reference count."],
    explanation: "unique_ptr has exclusive ownership with zero overhead. shared_ptr maintains an atomic reference count control block. When two objects hold shared_ptrs to each other, their ref counts stay at >= 1 forever, causing a circular memory leak. weak_ptr breaks the cycle by holding a non-owning weak reference that doesn't increment the strong reference count.",
    solution: "1. unique_ptr: Exclusive ownership, non-copyable, movable. O(1) delete upon scope exit.\n2. shared_ptr: Shared ownership via atomic reference counter control block.\n3. weak_ptr: Non-owning observer. Resolves circular references (e.g. parent-child graph nodes) by preventing reference count locks.",
    tags: ["C++", "Memory Management", "Pointers", "Qualcomm", "NVIDIA"],
    recommendedForRoles: ["Systems Engineer", "Embedded Software Engineer"],
    whyRecommended: "Core systems engineering benchmark for modern C++ memory safety.",
    createdAt: "2025-02-11T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── WEB & MODERN FULL STACK ────────────────────────────────────────
  {
    id: "qb-web-002",
    title: "WebSockets vs Server-Sent Events (SSE) vs HTTP Long-Polling",
    question: "Compare WebSockets, Server-Sent Events (SSE), and Long-Polling for real-time messaging. When is SSE superior to WebSockets?",
    type: "Conceptual",
    company: "Atlassian",
    role: "Full Stack Developer",
    round: "Technical Round 1",
    domain: "Web Development",
    topic: "Real-time Protocols",
    subtopic: "WebSockets & SSE",
    difficulty: "Medium",
    sourceType: "Community-Sourced Question",
    source: "Atlassian Confluence Team Interview",
    verified: true,
    hints: ["Is your data flow bidirectional or unidirectional? Does SSE support automatic reconnection and HTTP/2 multiplexing out of the box?"],
    explanation: "WebSockets offer full-duplex bidirectional communication over a single TCP connection after an HTTP 101 Switching Protocols handshake. SSE is unidirectional (server -> client) over standard HTTP, with built-in automatic reconnection, event IDs, and HTTP/2 multiplexing. SSE is superior for streaming AI responses (ChatGPT style) and notifications because it avoids custom protocol handling and firewall blocking.",
    solution: "1. WebSockets: Full-duplex bidirectional, TCP socket framing, requires custom heartbeats.\n2. SSE: Unidirectional (server-to-client), plain text/event-stream, built-in reconnection, multiplexes over HTTP/2.\n3. Long-polling: Fallback polling, high HTTP header overhead and latency.\nChoose SSE for generative AI token streaming, news tickers, and push notifications.",
    tags: ["Web Development", "WebSockets", "SSE", "Atlassian", "Slack"],
    recommendedForRoles: ["Full Stack Developer", "Frontend Developer", "Backend Developer"],
    whyRecommended: "Evaluates protocol selection trade-offs for modern real-time web applications.",
    createdAt: "2025-02-08T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── UBER GEOSPATIAL & ALGORITHMS ──────────────────────────────────
  {
    id: "qb-uber-001",
    title: "Design a Geospatial Driver Dispatch Matching System (H3 / Geohash)",
    question: "Design a low-latency driver dispatch engine capable of matching 100,000 active riders with nearby available drivers within a 3km radius under 200ms latency.",
    type: "System Design",
    company: "Uber",
    role: "Backend Developer",
    round: "System Design",
    domain: "System Design",
    topic: "Scalability",
    subtopic: "Geospatial Indexing",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Uber Core Dispatch Onsite Interview 2024",
    verified: true,
    hints: [
      "Traditional SQL spatial queries (ST_DWithin) fail at scale with millions of ping updates.",
      "Partition the globe into hexagonal grid cells using Uber's open-source H3 spatial index."
    ],
    explanation: "Uber partitions coordinates into hexagonal H3 cells. Hexagons have invariant distances to all 6 adjacent neighbors. Driver pings update an in-memory Redis cluster keyed by H3 index with a 10-second TTL.",
    solution: "1. Client sends lat/lng; server converts to H3 resolution 8 index.\n2. Query in-memory Redis set for the target H3 index and its immediate ring (k-ring 1).\n3. Filter available drivers, rank by ETA using routing matrix engine, and dispatch offer via WebSocket push.",
    tags: ["System Design", "Geospatial", "Uber", "Redis", "H3"],
    recommendedForRoles: ["Backend Developer", "System Architect", "SDE"],
    whyRecommended: "Classic Uber flagship architecture interview question testing spatial partitioning.",
    createdAt: "2025-02-22T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },
  {
    id: "qb-uber-002",
    title: "Rotting Oranges (Multi-Source BFS Traversal)",
    question: "You are given an m x n grid where each cell has 0 (empty), 1 (fresh orange), or 2 (rotten orange). Every minute, any fresh orange adjacent 4-directionally to a rotten orange becomes rotten. Return the minimum minutes until no fresh orange remains, or -1 if impossible.",
    type: "Coding",
    company: "Uber",
    role: "Software Engineer",
    round: "Coding Round",
    domain: "DSA",
    topic: "Graphs",
    subtopic: "BFS",
    difficulty: "Medium",
    sourceType: "Reported Question",
    source: "Uber SDE Campus Hiring Report",
    verified: true,
    testCases: [
      { input: "grid = [[2,1,1],[1,1,0],[0,1,1]]", expectedOutput: "4" },
      { input: "grid = [[2,1,1],[0,1,1],[1,0,1]]", expectedOutput: "-1" }
    ],
    hints: ["Add all initial rotten oranges (value 2) into a queue simultaneously.", "Process level-by-level (multi-source BFS), incrementing elapsed minutes."],
    explanation: "Standard multi-source Breadth First Search (BFS). All initial rotten oranges act as simultaneous infection sources expanding outward layer-by-layer.",
    solution: "Count fresh oranges. Enqueue all rotten (r, c) tuples. While queue is not empty and fresh > 0, expand current layer in 4 directions. For each valid adjacent fresh orange, convert to rotten, decrement fresh, and enqueue. Return fresh == 0 ? minutes : -1.",
    timeComplexity: "O(M * N)",
    spaceComplexity: "O(M * N)",
    tags: ["Graphs", "BFS", "Uber", "Amazon"],
    recommendedForRoles: ["Software Engineer", "AI/ML Engineer"],
    whyRecommended: "Essential multi-source BFS graph problem asked widely in campus coding rounds.",
    createdAt: "2025-01-20T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── APPLE HARDWARE & SYSTEMS ──────────────────────────────────────
  {
    id: "qb-appl-001",
    title: "Reverse Nodes in k-Group (Hard Linked List Manipulation)",
    question: "Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list. If the number of nodes is not a multiple of k, left-out nodes in the end should remain as-is.",
    type: "Coding",
    company: "Apple",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "DSA",
    topic: "Linked List",
    subtopic: "Two Pointers",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Apple CoreOS Engineering Interview",
    verified: true,
    testCases: [
      { input: "head = [1,2,3,4,5], k = 2", expectedOutput: "[2,1,4,3,5]" },
      { input: "head = [1,2,3,4,5], k = 3", expectedOutput: "[3,2,1,4,5]" }
    ],
    hints: ["Verify if k nodes exist ahead before reversing.", "Reverse exactly k nodes, reconnecting sublist head and tail."],
    explanation: "Iterate to count if k nodes remain. If so, iteratively reverse the k-node segment while reconnecting the previous segment's tail to the new subsegment head.",
    solution: "Use a dummy head. In a loop, find kth node from curr. If not found, break. Else save nextGroup = kth.next. Reverse between curr.next and kth. Reconnect pointers. Advance curr to the end of reversed segment.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    tags: ["Linked List", "Recursion", "Apple"],
    recommendedForRoles: ["Software Engineer", "Systems Engineer"],
    whyRecommended: "Rigorous test of pointer mutation and edge-case discipline without allocating auxiliary heap memory.",
    createdAt: "2025-02-14T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── ADOBE DOCUMENT & UI SYSTEMS ───────────────────────────────────
  {
    id: "qb-adbe-001",
    title: "Design an Undo-Redo Command Pattern for Rich Canvas Document Editors",
    question: "Implement an Undo-Redo engine for a canvas document editor with memory limits. How does the Command Pattern decouple user actions from document mutations?",
    type: "Conceptual",
    company: "Adobe",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "OOP",
    topic: "Design Patterns",
    subtopic: "SOLID Principles",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Adobe Photoshop Web Technical Round",
    verified: true,
    hints: ["Every action implements execute() and unexecute() / undo().", "Maintain two bounded stacks: undoStack and redoStack."],
    explanation: "The Command Pattern encapsulates a request as an object with both forward and inverse actions. When a new command executes, redoStack is cleared and the command is pushed onto undoStack.",
    solution: "1. Command interface with execute() and undo().\n2. Concrete commands (e.g. DrawShapeCommand, ResizeCommand) store previous snapshot delta.\n3. HistoryManager manages two bounded deque stacks (max depth 50 to conserve memory).\n4. Executing new action clears redoStack.",
    tags: ["OOP", "Design Patterns", "Adobe", "Web Development"],
    recommendedForRoles: ["Frontend Developer", "Software Engineer"],
    whyRecommended: "Fundamental architectural question for creative suite and document platform engineering.",
    createdAt: "2025-02-17T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── NVIDIA GPU & CONCURRENCY ───────────────────────────────────────
  {
    id: "qb-nvda-001",
    title: "Matrix Multiplication Cache Locality & Loop Tiling Optimization",
    question: "Explain why naive triple-nested loop matrix multiplication (i, j, k) suffers severe cache misses compared to loop tiling / blocked matrix multiplication.",
    type: "Conceptual",
    company: "NVIDIA",
    role: "Systems Engineer",
    round: "Technical Round 2",
    domain: "Operating Systems",
    topic: "Memory Management",
    subtopic: "CPU / GPU Cache",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "NVIDIA Deep Learning Hardware Architecture Round",
    verified: true,
    hints: ["Row-major vs column-major array traversal in memory.", "B[k][j] in naive multiplication accesses memory with stride N, causing continuous L1/L2 cache misses."],
    explanation: "Matrices stored in row-major order benefit from spatial locality when accessed sequentially along rows. In naive (i, j, k), matrix B is accessed column-wise with stride N, resulting in cold cache misses on every access. Loop tiling breaks the N x N matrix into B x B sub-blocks that fit entirely within L1 data cache.",
    solution: "1. Naive loop accesses B[k][j] across cache lines (stride N), causing 1 miss per multiplication.\n2. Swapping loop order to (i, k, j) keeps both A[i][k] invariant and B[k][j] in contiguous memory.\n3. Loop tiling / blocking segments matrix into tile sizes matching L1/shared memory capacity, reducing memory bus traffic from O(N^3) to O(N^3 / B).",
    tags: ["Systems", "Cache Locality", "NVIDIA", "CUDA", "Performance"],
    recommendedForRoles: ["Systems Engineer", "AI/ML Engineer"],
    whyRecommended: "Core question for high-performance computing, deep learning kernel optimization, and GPU compiler roles.",
    createdAt: "2025-02-25T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── WALMART SUPPLY CHAIN & GRAPHS ──────────────────────────────────
  {
    id: "qb-wmt-001",
    title: "Course Schedule II / Package Dependency Resolution (Topological Sort)",
    question: "Given numCourses and an array of prerequisite pairs, return the ordering of courses you should take to finish all courses. If impossible, return an empty array.",
    type: "Coding",
    company: "Walmart",
    role: "Software Engineer",
    round: "Online Assessment",
    domain: "DSA",
    topic: "Graphs",
    subtopic: "Topological Sort",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Walmart Global Tech Campus Drive",
    verified: true,
    testCases: [
      { input: "numCourses = 2, prerequisites = [[1,0]]", expectedOutput: "[0,1]" },
      { input: "numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]", expectedOutput: "[0,2,1,3]" }
    ],
    hints: ["Build an adjacency list and calculate in-degrees of all nodes.", "Kahn's Algorithm: enqueue all nodes with in-degree 0."],
    explanation: "Kahn's algorithm using BFS with in-degree tracking. If the number of processed nodes matches numCourses, a valid DAG topological order exists.",
    solution: "Calculate inDegree array for all nodes. Add inDegree==0 nodes to queue. While queue not empty, dequeue u, add to result, and decrement inDegree of all neighbors v. If inDegree[v] reaches 0, enqueue v. If result size != numCourses, return empty array.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V + E)",
    tags: ["Graphs", "Topological Sort", "Walmart", "Amazon"],
    recommendedForRoles: ["Software Engineer", "Backend Developer"],
    whyRecommended: "Standard topological ordering problem applied to package managers and build systems.",
    createdAt: "2025-01-28T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── MORGAN STANLEY & FINTECH ───────────────────────────────────────
  {
    id: "qb-ms-001",
    title: "Find Running Median from Data Stream with Two Heaps",
    question: "Design a data structure that supports adding integer numbers from a continuous stream and finding the median of all numbers seen so far in O(1) time.",
    type: "Coding",
    company: "Morgan Stanley",
    role: "Software Engineer",
    round: "Technical Round 1",
    domain: "DSA",
    topic: "Heaps",
    subtopic: "Dual Priority Queue",
    difficulty: "Hard",
    sourceType: "Verified Company Question",
    source: "Morgan Stanley Institutional Securities Screening",
    verified: true,
    testCases: [
      { input: "addNum(1); addNum(2); findMedian(); addNum(3); findMedian();", expectedOutput: "[1.5, 2.0]" }
    ],
    hints: ["Divide numbers into two halves: smaller half in maxHeap, larger half in minHeap.", "Ensure sizes differ by at most 1."],
    explanation: "A maxHeap stores the lower 50% of numbers, and a minHeap stores the upper 50%. The median is either the top of the larger heap or the average of both tops.",
    solution: "On addNum(x): insert into maxHeap. Move top of maxHeap to minHeap. If minHeap.size() > maxHeap.size(), balance by moving minHeap.top to maxHeap. Median: if maxHeap.size() > minHeap.size(), return maxHeap.top(); else return (maxHeap.top() + minHeap.top()) / 2.0.",
    timeComplexity: "O(log N) insert, O(1) findMedian",
    spaceComplexity: "O(N)",
    tags: ["Heaps", "Priority Queue", "Morgan Stanley", "Fintech"],
    recommendedForRoles: ["Software Engineer", "Quantitative Analyst"],
    whyRecommended: "Essential fintech streaming data structure evaluating dual heap equilibrium.",
    createdAt: "2025-02-04T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── JPMORGAN TRANSACTIONAL & CLOUD ─────────────────────────────────
  {
    id: "qb-jpm-001",
    title: "SQL Window Functions: Rolling 7-Day Fraud Transaction Volume",
    question: "Given a Transactions table (transaction_id, account_id, amount, transaction_time), write an SQL query to calculate the rolling 7-day cumulative spend for each account.",
    type: "SQL",
    company: "JPMorgan",
    role: "Data Analyst",
    round: "Technical Round 2",
    domain: "DBMS",
    topic: "SQL",
    subtopic: "Window Functions",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "JPMorgan Chase Quantitative Screening",
    verified: true,
    codeSnippet: `SELECT \n  account_id,\n  transaction_time,\n  amount,\n  SUM(amount) OVER (\n    PARTITION BY account_id\n    ORDER BY transaction_time\n    RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW\n  ) AS rolling_7day_spend\nFROM Transactions;`,
    hints: ["Use SUM() OVER with PARTITION BY account_id and RANGE BETWEEN INTERVAL."],
    explanation: "Window functions with temporal range clauses calculate moving aggregates without requiring expensive self-joins.",
    solution: "Use SUM(amount) OVER (PARTITION BY account_id ORDER BY transaction_time RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW) to calculate aggregate spending dynamically across arbitrary time intervals.",
    tags: ["SQL", "Window Functions", "JPMorgan", "Fintech"],
    recommendedForRoles: ["Data Analyst", "Data Scientist", "Backend Developer"],
    whyRecommended: "Essential SQL analytical query for banking anti-money laundering and velocity monitoring.",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── DELOITTE APTITUDE & CONSULTING ─────────────────────────────────
  {
    id: "qb-del-001",
    title: "Pipes, Cisterns & Flow Rate Efficiency",
    question: "Pipe A can fill a tank in 12 hours, and Pipe B can fill it in 15 hours. If both pipes are opened together and after 3 hours Pipe A is closed, how much additional time will Pipe B take to completely fill the tank?",
    type: "Aptitude",
    company: "Deloitte",
    role: "Software Engineer",
    round: "Online Assessment",
    domain: "Aptitude",
    topic: "Quantitative Ability",
    subtopic: "Time & Work",
    difficulty: "Easy",
    sourceType: "Verified Company Question",
    source: "Deloitte NLA Campus Assessment",
    verified: true,
    hints: ["Assume tank capacity is LCM(12, 15) = 60 units.", "Find combined unit flow per hour."],
    explanation: "Total work = LCM(12, 15) = 60 units. Rate of A = 5 units/hr. Rate of B = 4 units/hr. Together in 3 hours: 3 * (5 + 4) = 27 units. Remaining work: 60 - 27 = 33 units. Time for B: 33 / 4 = 8.25 hours (8 hours 15 minutes).",
    solution: "Rate A = 1/12, Rate B = 1/15. In 3 hours: 3 * (1/12 + 1/15) = 3 * (9/60) = 27/60 = 9/20. Remaining tank: 1 - 9/20 = 11/20. Time taken by B = (11/20) / (1/15) = 33/4 = 8 hours 15 minutes.",
    tags: ["Aptitude", "Time & Work", "Deloitte", "Campus Placement"],
    recommendedForRoles: ["Software Engineer", "Data Analyst"],
    whyRecommended: "Frequent quantitative screening puzzle in Big 4 and enterprise placement drives.",
    createdAt: "2025-01-10T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── CISCO NETWORKING & PROTOCOLS ───────────────────────────────────
  {
    id: "qb-csco-001",
    title: "TCP 3-Way Handshake vs TLS 1.3 Handshake Latency",
    question: "Explain the TCP 3-way handshake packet sequence (SYN, SYN-ACK, ACK) and how TLS 1.3 reduces round-trip times (RTT) compared to TLS 1.2 during encrypted connection setup.",
    type: "Conceptual",
    company: "Cisco",
    role: "Cloud Engineer",
    round: "Technical Round 1",
    domain: "Computer Networks",
    topic: "Protocols",
    subtopic: "TCP/IP & TLS",
    difficulty: "Medium",
    sourceType: "Verified Company Question",
    source: "Cisco Enterprise Networking Screening",
    verified: true,
    hints: ["TLS 1.2 required 2 full round trips for cipher negotiation and key exchange.", "TLS 1.3 piggybacks Diffie-Hellman key share in the ClientHello packet."],
    explanation: "TCP establishes transport connection in 1 RTT (SYN -> SYN-ACK -> ACK). TLS 1.2 required an additional 2 RTTs for crypto negotiation. TLS 1.3 achieves 1-RTT handshake by speculatively sending key shares with ClientHello, and supports 0-RTT resumption for returning clients.",
    solution: "1. TCP: Client SYN -> Server SYN-ACK -> Client ACK (1 RTT total).\n2. TLS 1.2: ClientHello -> ServerHello/Cert -> ClientKeyExchange -> Finished (2 RTTs).\n3. TLS 1.3: ClientHello includes DH key share; Server returns ServerHello + encrypted Finished in 1 RTT.\n4. TLS 1.3 0-RTT: Reuses pre-shared keys (PSK) to send encrypted application data in the very first packet.",
    tags: ["Computer Networks", "TCP/IP", "TLS 1.3", "Cisco"],
    recommendedForRoles: ["Cloud Engineer", "DevOps Engineer", "Backend Developer"],
    whyRecommended: "Core networking and security protocol evaluation essential for infrastructure and systems roles.",
    createdAt: "2025-01-18T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  },

  // ─── AI-GENERATED PRACTICE QUESTIONS (TRANSPARENTLY LABELED) ─────────
  {
    id: "qb-ai-prac-001",
    title: "Retrieval-Augmented Generation (RAG): Mitigating Vector Chunk Hallucinations",
    question: "In an enterprise RAG pipeline, how do you mitigate semantic retrieval mismatch when naive cosine similarity retrieves irrelevant chunks? Discuss Cross-Encoder Re-ranking vs Hybrid BM25 Keyword Search.",
    type: "AI/ML",
    company: "AI Practice Hub",
    role: "AI Engineer",
    round: "Technical Round 1",
    domain: "AI / ML",
    topic: "Generative AI",
    subtopic: "RAG & Vector Search",
    difficulty: "Hard",
    sourceType: "AI-Generated Practice Question",
    source: "Cognalyze AI Practice Synthesis",
    verified: false,
    hints: ["Dense bi-encoders compress entire chunks into single vectors, losing exact keyword matching.", "Cross-encoders evaluate query-document pairs simultaneously with full cross-attention."],
    explanation: "Dense vector embeddings frequently miss specific SKU identifiers or error codes that BM25 handles cleanly. Hybrid search fuses dense and sparse rankings using Reciprocal Rank Fusion (RRF), followed by a cross-encoder model to re-score top 20 candidates before LLM context injection.",
    solution: "1. Hybrid Retrieval: Run parallel Dense Vector Search + BM25 keyword query.\n2. Reciprocal Rank Fusion (RRF): Score = sum(1 / (k + rank_i)) combining rankings.\n3. Cross-Encoder Re-ranker: Pass top 30 chunks through transformer re-ranker (e.g. bge-reranker-large).\n4. Context Compression: Trim lowest scoring sentences to preserve LLM prompt token window.",
    tags: ["Generative AI", "RAG", "Vector Search", "LLM", "AI Practice"],
    recommendedForRoles: ["AI/ML Engineer", "Data Scientist", "Software Engineer"],
    whyRecommended: "Tests state-of-the-art Generative AI production engineering beyond basic vector databases.",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z"
  }
];

export const SUBTOPICS_BY_TOPIC: Record<string, string[]> = {
  DSA: [
    "Arrays",
    "Strings",
    "Linked List",
    "Stack",
    "Queue",
    "Trees",
    "Graphs",
    "Recursion",
    "Backtracking",
    "Greedy",
    "Dynamic Programming",
    "Binary Search",
    "Sliding Window",
    "Two Pointers",
    "Hashing",
    "Heaps"
  ],
  DBMS: [
    "SQL",
    "Joins",
    "Indexing",
    "Transactions",
    "ACID",
    "Normalization",
    "Concurrency",
    "Query Optimization",
    "Window Functions"
  ],
  "Operating Systems": [
    "Processes",
    "Threads",
    "Scheduling",
    "Deadlocks",
    "Memory Management",
    "Virtual Memory",
    "Synchronization"
  ],
  "Computer Networks": [
    "TCP/IP",
    "HTTP / HTTPS",
    "DNS",
    "Routing",
    "OSI Model",
    "Security & TLS",
    "WebSockets"
  ],
  OOP: [
    "Encapsulation",
    "Inheritance",
    "Polymorphism",
    "Abstraction",
    "SOLID Principles",
    "Design Patterns"
  ],
  "System Design": [
    "Scalability",
    "Caching & Redis",
    "Rate Limiting",
    "Message Queues & Kafka",
    "Microservices",
    "Geospatial Indexing"
  ],
  "AI / ML": [
    "Supervised Learning",
    "Neural Networks",
    "Model Evaluation",
    "Gradient Descent",
    "Generative AI",
    "RAG & Vector Search"
  ],
  "Generative AI": [
    "Prompt Engineering",
    "RAG Architecture",
    "Agent Tooling",
    "Vector Databases"
  ],
  "Web Development": [
    "Real-time Protocols",
    "State Management",
    "REST & GraphQL",
    "Performance Optimization"
  ],
  "HR / Behavioral": [
    "Leadership & Ownership",
    "Conflict Resolution",
    "STAR Method",
    "Collaboration"
  ],
  Aptitude: [
    "Quantitative Ability",
    "Time & Work",
    "Logical Reasoning",
    "Data Interpretation"
  ],
  Programming: [
    "C++ Memory & Pointers",
    "Java Garbage Collection",
    "Python Internals"
  ]
};

